import {test} from 'node:test';import assert from 'node:assert/strict';import {createState} from '../src/model/GameState';import {Dispatcher} from '../src/commands/Dispatcher';import {failBoss,retryBoss,type FailBoss,type RetryBoss} from '../src/commands/RetryBoss';import {stages} from '../src/content/StageConfig';import {rewardCatalog} from '../src/content/PlayableConfig';import {MemorySaveStore,FakeClock} from '../src/ports';import {TransactionCoordinator} from '../src/systems/TransactionCoordinator';import {recoverSave} from '../src/persistence/SaveRecovery';
test('timeout failure and free manual retry persist across reopen, reject stale/early calls, and cannot replay',async()=>{
 const store=new MemorySaveStore(),coordinator=new TransactionCoordinator(store,new FakeClock(10),'test'),reduce=(s:ReturnType<typeof createState>,c:FailBoss|RetryBoss)=>c.type==='FailBoss'?failBoss(s,c,stages,rewardCatalog,50):retryBoss(s,c,stages,rewardCatalog);
 let d=new Dispatcher(createState({dataVersion:'playable-v1',initialGold:'100',utcMs:0,firstStage:'stage_1_3'}),reduce,coordinator.commit);
 const fail:FailBoss={type:'FailBoss',commandId:'fail:1',stageId:'stage_1_3',sequence:0,waveOrdinal:0,tick:160,rng:[1,2,3,4]};assert.equal((await d.dispatch({...fail,commandId:'early',tick:159})).ok,false);store.failNext='write';assert.equal((await d.dispatch(fail)).ok,false);assert.equal(d.getSnapshot().data.stages.currentStageId,'stage_1_3');assert.equal((await d.dispatch(fail)).ok,true);assert.equal(d.getSnapshot().data.stages.currentStageId,'stage_1_2');assert.equal(d.getSnapshot().data.stages.bossRetryAvailable,true);
 const recovered=recoverSave(await store.readCandidates('test'),['playable-v1']);if(recovered.status!=='recovered')throw Error('Missing saved retry');d=new Dispatcher(recovered.state,reduce,coordinator.commit);
 const retry:RetryBoss={type:'RetryBoss',commandId:'retry:1',stageId:'stage_1_3',expectedSequence:1};await Promise.all([d.dispatch(retry),d.dispatch({...retry,commandId:'retry:2'})]);assert.equal(d.getSnapshot().data.stages.encounterSequence,2);assert.equal(d.getSnapshot().data.stages.currentStageId,'stage_1_3');assert.equal(d.getSnapshot().data.currencies.gold,'100');assert.equal(d.getSnapshot().data.progression.highestClearedOrdinal,0);
 await d.dispatch({...fail,commandId:'oldFailure'});assert.equal(d.getSnapshot().data.stages.currentStageId,'stage_1_3');assert.equal(d.getSnapshot().data.stages.encounterSequence,2);
});
