import {test} from 'node:test';import assert from 'node:assert/strict';import {chapterRecovery,validateRecoveryPolicy} from '../src/systems/RecoveryPolicy';import {BattleSystem} from '../src/systems/BattleSystem';import {battleConfig} from '../src/content/BattleConfig';import {spawnEncounter} from '../src/systems/EncounterSpawner';import {createState,snapshot} from '../src/model/GameState';import {heroes} from '../src/content/PlayableConfig';
test('unreviewed policies rejected; chapter enemy counterattacks explicitly disabled',()=>{
 assert.throws(()=>validateRecoveryPolicy({...chapterRecovery,evidence:'UNKNOWN' as any}));assert.throws(()=>validateRecoveryPolicy({...chapterRecovery,heroRecovery:'deleteOwnedHero' as any}));
 const enemy={id:'enemy',stats:{attack:100,defense:0,hp:10000,attackIntervalMs:50,critChanceBp:0,critMultiplierBp:10000},rewardId:null,canAttack:true,hitDelayMs:0};const encounter=spawnEncounter('stage1',0,0,[{enemyId:enemy.id,count:1}],[enemy],50),s=createState({dataVersion:'test',initialGold:'0',utcMs:0});const hero=heroes.instantiate('hero_tier_1','hero1',0);hero.deployed=true;s.data.heroes=[hero];s.data.board[0]!.unitId=hero.id;const original=snapshot(s);
 const passive=new BattleSystem(encounter,battleConfig,[1,2,3,4]);passive.syncRoster(original,heroes);passive.step();assert.equal(passive.snapshot().encounter.entities.find(e=>e.side==='hero')!.hp,100);
 const counter=new BattleSystem(encounter,battleConfig,[1,2,3,4],{...chapterRecovery,id:'counterattack-fixture',enemyCounterattacks:true});counter.syncRoster(original,heroes);counter.step();assert.equal(counter.snapshot().encounter.entities.find(e=>e.side==='hero')!.hp,0);assert.deepEqual(s,original);
 s.data.heroes[0]!.deployed=false;counter.syncRoster(snapshot(s),heroes);s.data.heroes[0]!.deployed=true;counter.syncRoster(snapshot(s),heroes);assert.equal(counter.snapshot().encounter.entities.find(e=>e.side==='hero')!.hp,0);
 const next=new BattleSystem({...encounter,id:'next'},battleConfig,[1,2,3,4]);next.syncRoster(snapshot(s),heroes);assert.equal(next.snapshot().encounter.entities.find(e=>e.side==='hero')!.hp,100);assert.equal(s.data.heroes.length,1);
});
