import {test} from 'node:test';import assert from 'node:assert/strict';import {UnlockService} from '../src/systems/UnlockService';import {unlocks} from '../src/content/UnlockConfig';import {createState} from '../src/model/GameState';import {unlockBoard} from '../src/model/Board';import {boardConfig} from '../src/content/PlayableConfig';import {decodeSave,encodeSave} from '../src/persistence/SaveCodec';
test('nested allOf/anyOf respects each threshold; invalid/cyclic conditions cannot be enabled',()=>{
 const service=new UnlockService([{id:'mixed',condition:{kind:'allOf',conditions:[{kind:'stageAtLeast',value:3},{kind:'anyOf',conditions:[{kind:'tierAtLeast',value:4},{kind:'accountLevelAtLeast',value:2}]}]},popupKey:'mixed',targetFeatureId:'mixed',tutorialStepId:null}]);const s=createState({dataVersion:'playable-v1',initialGold:'0',utcMs:0});s.data.progression.highestClearedOrdinal=3;assert.equal(service.evaluate(s).length,0);s.data.progression.discoveredTiers=[4];assert.equal(service.evaluate(s).length,1);assert.equal(service.evaluate(s).length,0);
 const cyclic:any={kind:'allOf',conditions:[]};cyclic.conditions=[cyclic];assert.throws(()=>new UnlockService([{...service.rules[0]!,condition:cyclic}]));
});
test('stage-three/final clears open rows; announcements survive reload independently and once only',()=>{
 let s=createState({dataVersion:'playable-v1',initialGold:'0',utcMs:0,unlockedSlots:5});s.data.progression.highestClearedOrdinal=2;assert.equal(unlocks.evaluate(s).length,0);s.data.progression.highestClearedOrdinal=3;assert.equal(unlocks.evaluate(s).length,5);assert.deepEqual(unlockBoard(s,boardConfig),[5,6,7,8,9]);assert.equal(unlocks.pending(s).length,5);
 const c={type:'AnnounceUnlocks' as const,commandId:'announce:row2',ids:unlocks.pending(s).map(r=>r.id)};unlocks.announce(s,c);s=decodeSave(encodeSave(s));unlocks.announce(s,c);assert.equal(unlocks.pending(s).length,0);assert.equal(s.data.unlocks.announcedIds.length,5);s.data.progression.highestClearedOrdinal=6;assert.equal(unlocks.evaluate(s).length,5);assert.deepEqual(unlockBoard(s,boardConfig),[10,11,12,13,14]);assert.equal(unlocks.announce(s,{...c,ids:['missing']}).ok,false);
});
