// One integration check at the new native adapter boundary; existing core rules are reused.
const ts=require('typescript'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const cache=new Map(),storage=new Map();
function load(file){
 file=path.resolve(file);if(!fs.existsSync(file))file=file.replace(/\.ts$/,'/index.ts');if(cache.has(file))return cache.get(file);
 const module={exports:{}};cache.set(file,module.exports);
 const out=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 new Function('require','module','exports',out)(name=>name==='cc'?{sys:{localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)}}}:load(path.resolve(path.dirname(file),name+'.ts')),module,module.exports);return module.exports;
}
(async()=>{
 const {BattleModel}=load(path.join(__dirname,'../assets/scripts/BattleModel.ts')),events=[],m=new BattleModel(e=>events.push(e));await m.init();
 assert.equal(m.gold,100);await m.command('BuyHero',{offerId:'buy_tier_1'});assert.equal(m.snapshot.data.player.tutorialState,'step_2');await m.command('BuyHero',{offerId:'buy_tier_1'});assert.equal(m.snapshot.data.player.tutorialState,'step_3');
 const [a,b]=m.heroes;await m.command('MergeHeroes',{sourceId:'hero_'+a.id,targetId:'hero_'+b.id});assert.equal(m.heroes[0].tier,2);
 const hero=m.heroes[0];await m.command('MoveHero',{heroId:'hero_'+hero.id,slotId:0});await m.command('DeployHero',{heroId:'hero_'+hero.id,deployed:true});
 assert.equal(m.snapshot.data.player.tutorialState,'step_5','Deployment alone does not complete onboarding');
 const advance=async(n,until=()=>false)=>{for(let i=0;i<n&&!until();i++){m.update(.05);await new Promise(r=>setImmediate(r));}};
 await advance(40,()=>events.some(e=>e.type==='attack'));
 assert.equal(events.find(e=>e.type==='attack').flightSeconds,.5);const hp=m.hp;
 await advance(9);assert.equal(m.hp,hp,'No early damage before the projectile deadline');
 await advance(1);assert.ok(m.hp<hp,'Simulation hit resolves at 500 ms, independent of VFX');
 await advance(200,()=>events.some(e=>e.type==='clear'));
 assert.equal(m.kills,1);const gold=m.gold;
 assert.deepEqual(events.find(e=>e.type==='reward').rewards,{gold:'6',gem:'1'},'Kill + first-clear rewards aggregate once');
 await advance(20,()=>m.stage.name==='1-2');assert.equal(m.stage.name,'1-2','Next stage starts without Continue');
 assert.equal(m.gold,gold,'Automatic transition never repeats the reward');
 const beforeHits=events.filter(e=>e.type==='hit').length;
 await advance(80,()=>events.filter(e=>e.type==='hit').length>beforeHits);
 assert.ok(events.filter(e=>e.type==='hit').length>beforeHits,'Combat continues in the next stage');
 assert.equal(m.gold,gold);
 assert.equal(m.snapshot.data.player.tutorialState,'completed','Real combat completes the saved guide');
 const {RewardCounter}=load(path.join(__dirname,'../assets/scripts/RewardCounter.ts')),counter=new RewardCounter();
 const amount='9007199254740997',arrive=counter.reserve('gold',amount,5);
 assert.equal(counter.display('gold',amount),'0');
 for(const i of [3,0,4,1,2])assert.equal(arrive(i),true);
 assert.equal(arrive(2),false);assert.equal(counter.display('gold',amount),amount);
 const cancelled=counter.reserve('gem','7',3);assert.equal(counter.display('gem','3'),'0');counter.clear();assert.equal(cancelled(0),false);assert.equal(counter.display('gem','7'),'7');
 await m.command('ReserveDaily');const period=m.snapshot.data.daily.pendingPeriod;assert.notEqual(period,null);assert.equal(await m.command('ClaimDaily',{period}),true);assert.equal(m.gold,gold+5000);
 const {BATTLE_PANEL_TOP,BATTLE_ROW_GAP,BATTLE_SLOT_TOP,battleBoardTop,battleBoostTop,battleDropArea,insideBattle}=load(path.join(__dirname,'../assets/scripts/BattleLayout.ts'));
 for(const height of [430*640/360,932,956]){
  const boardTop=battleBoardTop(height),boostTop=battleBoostTop(height),area=battleDropArea(boardTop),hero={x:49,y:boardTop+24},drop={x:215,y:area.y+area.h/2};
  assert.ok(boostTop>boardTop-57,'Boost controls must begin below the actor ground line');
  assert.ok(boostTop+48+8<=boardTop+BATTLE_PANEL_TOP,'Boost controls need a visible gap above the merge panel');
  assert.ok(boardTop+2*BATTLE_ROW_GAP+BATTLE_SLOT_TOP+46<=height-171,'The last merge row must stay above purchase cards');
  assert.ok(area.h>=150);assert.equal(insideBattle(hero.x,hero.y,boardTop),false,'Tutorial drag must start on the reserve hero, outside battle');
  assert.ok(drop.y<boardTop-18,'Tutorial target must stay above the reserve board');
  for(const y of [area.y,drop.y,area.y+area.h])assert.ok(insideBattle(drop.x,y,boardTop),'The spotlight and release path must use the same accepted battle area');
  assert.equal(insideBattle(drop.x,boardTop,boardTop),false);
 }
 const {equipmentDefinitions}=load(path.join(__dirname,'../assets/scripts/core/content/EquipmentConfig.ts')),{equipmentPrice}=load(path.join(__dirname,'../assets/scripts/core/commands/BuyEquipment.ts'));
 const own=m.snapshot.data.heroes[0],offer=equipmentDefinitions.find(e=>e.heroDefinitionId===own.definitionId),price=equipmentPrice(offer),beforeBuy=m.gold;
 const purchase={type:'BuyEquipment',commandId:'store-test-purchase',heroId:own.id,definitionId:offer.id,expectedCost:price};
 assert.equal((await m.game.dispatcher.dispatch(purchase)).ok,true);assert.equal(m.gold,beforeBuy-Number(price));assert.equal(m.snapshot.data.equipment.find(e=>e.definitionId===offer.id).ownerHeroId,own.id);
 assert.equal((await m.game.dispatcher.dispatch(purchase)).ok,true);assert.equal(m.gold,beforeBuy-Number(price),'Duplicate receipt cannot spend twice');
 assert.equal((await m.game.dispatcher.dispatch({...purchase,commandId:'store-second-click'})).ok,false);assert.equal(m.gold,beforeBuy-Number(price),'Owned item cannot be purchased twice');
 const otherOffer=equipmentDefinitions.find(e=>e.heroDefinitionId===own.definitionId&&e.slotType!==offer.slotType);
 const snapshot=JSON.stringify(m.snapshot.data);
 assert.equal(await m.command('BuyEquipment',{heroId:own.id,definitionId:otherOffer.id,expectedCost:'0'}),false);assert.equal(JSON.stringify(m.snapshot.data),snapshot,'Stale price leaves saved state untouched');
 // Missing/unavailable video never grants money. Actual SDK inventory needs owner ID.
 await m.command('BeginFreeCoinsAd');const op=Object.values(m.snapshot.data.rewardedOperations).find(o=>o.placement==='freeCoins'&&o.status==='reserved'),adGold=m.gold;
 assert.equal(await m.command('ClaimFreeCoins',{operationId:op.id}),false);assert.equal(m.gold,adGold);
 await m.command('RecordFreeCoinsAd',{result:{id:op.id,placement:op.placement,outcomeId:op.outcomeId,sessionId:op.sessionId,status:'unavailable'}});
 assert.equal(await m.command('ClaimFreeCoins',{operationId:op.id}),false);assert.equal(m.gold,adGold);
 await m.command('OpenRelics',{count:1});assert.ok(Object.keys(m.snapshot.data.relics).length);
 const before=JSON.stringify(m.snapshot.data);await m.game.flush();m.dispose();const restored=new BattleModel(()=>{});await restored.init();assert.deepEqual(restored.snapshot.data,JSON.parse(before));restored.dispose();
 const {migrateProgress}=load(path.join(__dirname,'../assets/scripts/runtime/ProgressMigration.ts'));
 const legacy=JSON.parse(JSON.stringify(restored.snapshot));legacy.dataVersion='playable-v1';legacy.data.stages={currentStageId:'stage_1_5',encounterSequence:100,waveOrdinal:1,bossRetryAvailable:true,farmStageId:'stage_1_5'};legacy.data.progression.highestClearedOrdinal=5;
 const money=JSON.stringify(legacy.data.currencies),owned=JSON.stringify(legacy.data.heroes),receipts=JSON.stringify(legacy.data.transactionReceipts);
 assert.equal(migrateProgress(legacy),true);assert.equal(legacy.data.stages.currentStageId,'stage_2_9');assert.equal(legacy.data.progression.highestClearedOrdinal,19);assert.equal(migrateProgress(legacy),false);
 assert.equal(JSON.stringify(legacy.data.currencies),money);assert.equal(JSON.stringify(legacy.data.heroes),owned);assert.equal(JSON.stringify(legacy.data.transactionReceipts),receipts);assert.ok(Object.hasOwn(legacy.data.sourceWatermarks,'stageFirstClear:stage_2_9'));
 const {GameRuntime}=load(path.join(__dirname,'../assets/scripts/runtime/GameRuntime.ts')),{BattleRuntime}=load(path.join(__dirname,'../assets/scripts/runtime/BattleRuntime.ts'));
 const fixture=JSON.parse(JSON.stringify(restored.snapshot));fixture.data.stages={currentStageId:'stage_1_1',encounterSequence:1000,waveOrdinal:0,bossRetryAvailable:false,farmStageId:null};fixture.data.heroes[0].tier=4;fixture.data.heroes[0].definitionId='hero_tier_4';
 const g=new GameRuntime(fixture,async()=>{}),btl=new BattleRuntime(g);btl.setCocosPaused(false);const visited=new Set();
 const tick=async()=>{btl.advance(50);await new Promise(r=>setImmediate(r));visited.add(btl.getSnapshot().stageId);};
 for(let i=0;i<4000&&!btl.getSnapshot().boss;i++)await tick();
 assert.equal(btl.getSnapshot().stageId,'stage_1_10');for(let n=1;n<=10;n++)assert.ok(visited.has('stage_1_'+n),'Stage '+n+' must be reachable in order');
 for(let i=0;i<450&&btl.getSnapshot().boss;i++)await tick();
 assert.equal(btl.getSnapshot().stageId,'stage_1_9');assert.equal(g.dispatcher.getSnapshot().data.stages.bossRetryAvailable,true);
 const looks=new Set();for(let i=0;i<500;i++){await tick();looks.add(btl.getSnapshot().combat.encounter.entities.find(e=>e.side==='enemy').definitionId);}
 assert.equal(btl.getSnapshot().stageId,'stage_1_9','Farming never bounces stage numbers');assert.ok(looks.size>=3,'Use varied owned enemy art');
 const stagesNow=g.dispatcher.getSnapshot().data.stages;const retry=await g.dispatcher.dispatch({type:'RetryBoss',commandId:g.nextId('retry'),stageId:'stage_1_10',expectedSequence:stagesNow.encounterSequence});assert.equal(retry.ok,true);assert.equal(btl.getSnapshot().stageId,'stage_1_10');btl.dispose();
 const {deploymentCapacity}=load(path.join(__dirname,'../assets/scripts/core/systems/AccountProgression.ts'));
 const capState=JSON.parse(JSON.stringify(restored.snapshot));capState.data.player.accountLevel=2;capState.data.player.xp='100';capState.data.progression.deploymentCapacity=2;capState.data.progression.highestClearedOrdinal=19;
 capState.data.board.forEach((slot,i)=>slot.unlocked=i<10);capState.data.unlocks.unlockedIds=Array.from({length:5},(_,i)=>'slot_'+(i+5));
 capState.data.stages={currentStageId:'stage_2_10',encounterSequence:1200,waveOrdinal:0,bossRetryAvailable:false,farmStageId:null};
 const cg=new GameRuntime(capState,async()=>{}),capacityEvents=[];cg.dispatcher.events.subscribe(es=>capacityEvents.push(...es.filter(e=>e.type==='deployment.capacityUnlocked')));
 for(let i=0;i<3;i++)assert.equal((await cg.dispatcher.dispatch({type:'BuyHero',offerId:'buy_tier_1',commandId:'cap-buy-'+i})).ok,true);
 const reserve=cg.dispatcher.getSnapshot().data.heroes.filter(h=>!h.deployed);assert.equal(reserve.length,2);
 assert.equal((await cg.dispatcher.dispatch({type:'DeployHero',heroId:reserve[0].id,deployed:true,commandId:'early-third'})).reason,'DEPLOYMENT_FULL');
 const encounterId='stage_2_10:1200:0',entityId=encounterId+':enemy:0';
 const clear={type:'ClaimBattleRewards',commandId:'last-row-boss-clear',encounterId,waveOrdinal:0,rewards:[{encounterId,entityId,rewardId:'kill_2_10',source:'kill:'+encounterId+':'+entityId}],cleared:true,rng:[1,2,3,4]};
 assert.equal((await cg.dispatcher.dispatch(clear)).ok,true);assert.equal(cg.dispatcher.getSnapshot().data.board.filter(s=>s.unlocked).length,15);assert.equal(deploymentCapacity(cg.dispatcher.getSnapshot()),3);assert.equal(cg.dispatcher.getSnapshot().data.progression.deploymentCapacity,3);
 assert.equal((await cg.dispatcher.dispatch({type:'DeployHero',heroId:reserve[0].id,deployed:true,commandId:'earned-third'})).ok,true);
 assert.equal((await cg.dispatcher.dispatch({type:'DeployHero',heroId:reserve[1].id,deployed:true,commandId:'fourth-blocked'})).reason,'DEPLOYMENT_FULL');
 await cg.dispatcher.dispatch(clear);assert.equal(capacityEvents.length,1,'One durable third-capacity grant');
 const {checksum,decodeSave,encodeSave}=load(path.join(__dirname,'../assets/scripts/core/persistence/SaveCodec.ts'));
 const oldFull=JSON.parse(JSON.stringify(cg.dispatcher.getSnapshot()));oldFull.data.progression.deploymentCapacity=2;oldFull.data.heroes.find(h=>h.id===reserve[0].id).deployed=false;
 const payload=JSON.stringify(oldFull),bytes=JSON.stringify({format:1,payload,checksum:checksum(payload)});assert.equal(decodeSave(bytes).data.progression.deploymentCapacity,2);assert.throws(()=>encodeSave(oldFull));
 storage.clear();storage.set('mergeheroes.cocos.v1:A',bytes);
 const repaired=new BattleModel(()=>{});await repaired.init();assert.equal(repaired.capacity,3);assert.equal(repaired.snapshot.data.progression.deploymentCapacity,3);assert.deepEqual(repaired.snapshot.data.currencies,oldFull.data.currencies);assert.deepEqual(repaired.snapshot.data.heroes,oldFull.data.heroes);repaired.dispose();
 const {redDots}=load(path.join(__dirname,'../assets/scripts/core/selectors/RedDots.ts')),badgeState=JSON.parse(JSON.stringify(restored.snapshot)),now=Date.now();
 badgeState.data.daily.lastClaimedPeriod=null;assert.equal(redDots(badgeState,now).daily,true);badgeState.data.daily.lastClaimedPeriod=Math.floor(now/86400000);assert.equal(redDots(badgeState,now).daily,false);assert.equal(redDots(badgeState,now+86400000).daily,true);
 badgeState.data.wheel={nextFreeAt:now+60000,freeSpins:0,pendingSpin:null};assert.equal(redDots(badgeState,now).wheel,false);assert.equal(redDots(badgeState,now+60000).wheel,true);
 const {heroSaleGold}=load(path.join(__dirname,'../assets/scripts/core/commands/SellHero.ts'));
 const saleGame=new GameRuntime(JSON.parse(JSON.stringify(restored.snapshot)),async()=>{}),sellId=saleGame.dispatcher.getSnapshot().data.heroes[0].id;
 const saleBefore=saleGame.dispatcher.getSnapshot(),salePrice=heroSaleGold(saleBefore,sellId),saleGold=BigInt(saleBefore.data.currencies.gold),itemCount=saleBefore.data.equipment.length;
 assert.ok(saleBefore.data.heroes[0].deployed);assert.ok(saleBefore.data.equipment.some(i=>i.ownerHeroId===sellId));
 const sale={type:'SellHero',commandId:'sell-deployed',heroId:sellId,expectedGold:salePrice};
 assert.equal((await saleGame.dispatcher.dispatch(sale)).ok,true);
 const sold=saleGame.dispatcher.getSnapshot();assert.equal(sold.data.heroes.length,0);assert.ok(sold.data.board.every(s=>s.unitId!==sellId));assert.ok(sold.data.equipment.every(i=>i.ownerHeroId===null));assert.equal(sold.data.equipment.length,itemCount);assert.equal(BigInt(sold.data.currencies.gold),saleGold+BigInt(salePrice));
 assert.equal((await saleGame.dispatcher.dispatch(sale)).ok,true);assert.equal(saleGame.dispatcher.getSnapshot().data.currencies.gold,sold.data.currencies.gold);
 const recoveredSale=new GameRuntime(decodeSave(encodeSave(sold)),async()=>{});assert.equal((await recoveredSale.dispatcher.dispatch({...sale,commandId:'sell-again-after-restart'})).ok,true);assert.equal(recoveredSale.dispatcher.getSnapshot().data.currencies.gold,sold.data.currencies.gold);
 assert.equal((await recoveredSale.dispatcher.dispatch({type:'BuyHero',commandId:'recruit-after-last-sale',offerId:'buy_tier_1'})).ok,true);
 const reserveId=recoveredSale.dispatcher.getSnapshot().data.heroes[0].id,wrongQuote={type:'SellHero',commandId:'wrong-sale-quote',heroId:reserveId,expectedGold:'0'};
 assert.equal((await recoveredSale.dispatcher.dispatch(wrongQuote)).ok,false);
 assert.equal((await recoveredSale.dispatcher.dispatch({...wrongQuote,commandId:'sell-reserve',expectedGold:heroSaleGold(recoveredSale.dispatcher.getSnapshot(),reserveId)})).ok,true);
 console.log('PASS: tutorial/combat/rewards/persistence; 16:9 and tall deployment geometry; equipment purchase/equip/idempotency/stale-price; no unconfirmed ad grant; deployed/reserve hero sale, equipment preserved, duplicate/restart safety and last-hero recovery.');
})().catch(e=>{console.error(e);process.exitCode=1;});
