import fs from 'node:fs/promises';import sharp from 'sharp';import crypto from 'node:crypto';
async function main(){
const base=JSON.parse(await fs.readFile('app/assets/asset-registry.json','utf8')).records;
const policy=JSON.parse(await fs.readFile('app/assets/runtime-texture-policy.json','utf8'));
await fs.mkdir('app/assets/art/variants',{recursive:true});const records=[];
for(const entry of base){
 if(entry.id.startsWith('background_floating'))continue;
 for(const edge of (policy.density512.includes(entry.id)?[128,256,512]:[128,256])){
  if(Math.max(entry.width,entry.height)<=edge)continue;
  const bytes=await fs.readFile(entry.sourceFile);
  if(crypto.createHash('sha256').update(bytes).digest('hex')!==entry.sourceSha256)throw Error('changed source');
  const out=await sharp(bytes).resize(edge,edge,{fit:'inside',withoutEnlargement:true}).png({compressionLevel:9}).toBuffer({resolveWithObject:true});const file=`app/assets/art/variants/${entry.id}-${edge}.png`;await fs.writeFile(file,out.data);
  records.push({id:entry.id,edge,file,width:out.info.width,height:out.info.height,sourceSha256:entry.sourceSha256,sha256:crypto.createHash('sha256').update(out.data).digest('hex'),trimApplied:false});
 }
}
await fs.writeFile('app/assets/variants.json',JSON.stringify({purpose:'Pixel-density-aware full-canvas derivatives; semantic identity and original art preserved',records},null,2)+'\n');
let code='// Generated by derive-variants.ts; full-canvas derivatives of the semantic source.\nexport const variants: Record<string, Partial<Record<number, number>>> = {\n';
for(const entry of base){const r=records.filter(r=>r.id===entry.id);if(r.length)code+=`${JSON.stringify(entry.id)}: {${r.map(r=>`${r.edge}: require('../../assets/art/variants/${r.id}-${r.edge}.png')`).join(',')}},\n`;}
await fs.writeFile('app/src/assets/variants.ts',code+'};\n');console.log('Density variants:',records.length);

}
main().catch(e=>{console.error(e);process.exitCode=1;});
