import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';
const root = process.cwd();
const read = async (p: string) => JSON.parse(await fs.readFile(p, 'utf8'));
const hash = (b: Buffer) => crypto.createHash('sha256').update(b).digest('hex');
async function main() {
  const semantic = await read('analysis/figma/semantic_map.json');
  const plan = await read('analysis/figma/atlas_plan.json');
  const calibration = await read('analysis/figma/import_calibration.json');
  const texturePolicy = await read('app/assets/runtime-texture-policy.json');
  const args = process.argv.slice(2);
  const screenIds = args.filter(a => !a.startsWith('--')).length ? args.filter(a => !a.startsWith('--')) : ['SCREEN-003'];
  const existing = await read('app/assets/asset-registry.json').catch(()=>({records:[],screenIds:[]}));
  const retained = new Set(existing.records.map((a:any)=>a.id));
  const selected = plan.records.filter((a: any) => retained.has(a.semanticId) || args.includes('--enemies') && a.semanticId.startsWith('enemy_') || args.includes('--bosses') && a.semanticId.startsWith('boss_') || args.includes('--equipment') && /^(equipment_|portrait_)/.test(a.semanticId) || a.screens.some((s: string) => screenIds.includes(s)) || a.semanticId.startsWith('hero_') && a.runtimeSize[0] > 0);
  // Small, shipped equipment variants may have no atlas entry. Their semantic
  // source and calibration still exist; import only actual catalog references.
  const equipmentSource=await fs.readFile('game-core/src/content/EquipmentConfig.ts','utf8');
  for(const [,id] of equipmentSource.matchAll(/"visualId": "([^"]+)"/g)){
    if(selected.some((a:any)=>a.semanticId===id))continue;
    const s=semantic.find((a:any)=>a.semanticId===id);
    if(!s||s.scope==='UNUSED_OR_REFERENCE_ONLY')throw Error(`Missing shipped equipment source: ${id}`);
    selected.push({semanticId:id,sourceFile:s.sourceFile,sourceSha256:hash(await fs.readFile(s.sourceFile)),runtimeSize:s.sourceDimensions.map((n:number)=>Math.round(n*Math.min(1,384/Math.max(...s.sourceDimensions)))),group:'equipment_icons',screens:[]});
  }
  await fs.mkdir('app/assets/art', { recursive: true });
  await fs.mkdir('app/src/assets', { recursive: true });
  const records = [];
  for (const entry of selected) {
    const source = semantic.find((a: any) => a.semanticId === entry.semanticId);
    const meta = calibration.records.find((a: any) => a.semanticId === entry.semanticId);
    if (!source || !meta || source.scope === 'UNUSED_OR_REFERENCE_ONLY') throw Error(`Invalid source selection: ${entry.semanticId}`);
    const bytes = await fs.readFile(entry.sourceFile);
    if (hash(bytes) !== entry.sourceSha256) throw Error(`Source hash mismatch: ${entry.semanticId}`);
    const file = `app/assets/art/${entry.semanticId}.png`;
    // Resize complete source canvas, never trim feet/glow or infer an alpha crop.
    const cap=texturePolicy.caps.find((c:any)=>c.id===entry.semanticId)?.maxEdge;
    const result = await sharp(bytes).resize(cap??entry.runtimeSize[0], cap??entry.runtimeSize[1], { fit: 'inside', withoutEnlargement: true }).png({ compressionLevel: 9 }).toBuffer({ resolveWithObject: true });
    await fs.writeFile(file, result.data);
    records.push({ id: entry.semanticId, file, sourceFile: entry.sourceFile, sourceSha256: entry.sourceSha256, sha256: hash(result.data), width: result.info.width, height: result.info.height, originalSize: source.sourceDimensions, pivot: meta.pivot.normalizedTopLeft, trim: { applied: false, offset: [0, 0] }, group: entry.group, scope: source.scope, distributionAllowed: false });
  }
  await fs.mkdir('app/assets/fonts', { recursive: true });
  for (const [source, target] of [['passionone/PassionOne-Regular.ttf','PassionOne-Regular.ttf'],['passionone/PassionOne-Bold.ttf','PassionOne-Bold.ttf'],['nunito/Nunito[wght].ttf','Nunito.ttf'],['roboto/Roboto[wdth,wght].ttf','Roboto.ttf']]) await fs.copyFile(`analysis/figma/fonts/source/${source}`, `app/assets/fonts/${target}`);
  const body = `// Generated by tooling/assets/import-figma.ts; source semantic IDs are authoritative.\nexport const art = {\n${records.map(a => `  ${JSON.stringify(a.id)}: require(${JSON.stringify('../../assets/art/'+a.id+'.png')}),`).join('\n')}\n} as const;\nexport type AssetId = keyof typeof art;\n`;
  await fs.writeFile('app/src/assets/registry.ts', body);
  await fs.writeFile('app/assets/asset-registry.json', JSON.stringify({ version: 1, screenIds:[...new Set([...existing.screenIds,...screenIds])], records }, null, 2)+'\n');
  console.log(JSON.stringify({ imported: records.length, decodedMiB: records.reduce((n,a) => n+a.width*a.height*4,0)/1024**2, sourcePreserved: true }));
}
main().catch(error => { console.error(error); process.exitCode=1; });
