import fs from 'node:fs/promises';import crypto from 'node:crypto';import sharp from 'sharp';
const hash=(b:Buffer)=>crypto.createHash('sha256').update(b).digest('hex');
async function main(){
 const registry=JSON.parse(await fs.readFile('app/assets/asset-registry.json','utf8')),density=JSON.parse(await fs.readFile('app/assets/variants.json','utf8')),policy=JSON.parse(await fs.readFile('app/assets/runtime-texture-policy.json','utf8'));
 let oldBytes=0,newBytes=0,oldRgba=0,newRgba=0;
 for(const cap of policy.caps){
  const a=registry.records.find((a:any)=>a.id===cap.id);if(!a)throw Error('Missing reviewed asset');
  const source=await fs.readFile(a.sourceFile);if(hash(source)!==a.sourceSha256)throw Error('Changed source');
  const out=await sharp(source).resize(cap.maxEdge,cap.maxEdge,{fit:'inside',withoutEnlargement:true}).png({compressionLevel:9}).toBuffer({resolveWithObject:true});
  oldBytes+=(await fs.stat(a.file)).size;oldRgba+=a.width*a.height*4;newBytes+=out.data.length;newRgba+=out.info.width*out.info.height*4;
  if(hash(out.data)!==a.sha256)await fs.writeFile(a.file,out.data);
  Object.assign(a,{width:out.info.width,height:out.info.height,sha256:hash(out.data)});
 }
 for(const id of policy.density512){
  const a=registry.records.find((a:any)=>a.id===id);if(!a||Math.max(a.width,a.height)<=512)throw Error('Invalid reviewed derivative');
  const source=await fs.readFile(a.sourceFile);if(hash(source)!==a.sourceSha256)throw Error('Changed source');
  const out=await sharp(source).resize(512,512,{fit:'inside',withoutEnlargement:true}).png({compressionLevel:9}).toBuffer({resolveWithObject:true}),file=`app/assets/art/variants/${id}-512.png`;
  await fs.writeFile(file,out.data);density.records=density.records.filter((v:any)=>!(v.id===id&&v.edge===512));density.records.push({id,edge:512,file,width:out.info.width,height:out.info.height,sourceSha256:a.sourceSha256,sha256:hash(out.data),trimApplied:false});
 }
 density.records.sort((a:any,b:any)=>a.id.localeCompare(b.id)||a.edge-b.edge);
 await fs.writeFile('app/assets/asset-registry.json',JSON.stringify(registry,null,2)+'\n');await fs.writeFile('app/assets/variants.json',JSON.stringify(density,null,2)+'\n');
 let code='// Generated by derive-variants.ts; full-canvas derivatives of the semantic source.\nexport const variants: Record<string, Partial<Record<number, number>>> = {\n';
 for(const a of registry.records){const rows=density.records.filter((v:any)=>v.id===a.id);if(rows.length)code+=`${JSON.stringify(a.id)}: {${rows.map((v:any)=>`${v.edge}: require('../../assets/art/variants/${v.id}-${v.edge}.png')`).join(',')}},\n`;}
 await fs.writeFile('app/src/assets/variants.ts',code+'};\n');console.log({reviewedCaps:policy.caps.length,derivatives:policy.density512.length,oldMiB:oldBytes/1024**2,newMiB:newBytes/1024**2,oldRgbaMiB:oldRgba/1024**2,newRgbaMiB:newRgba/1024**2});
}
main().catch(e=>{console.error(e);process.exitCode=1;});
