"""Validate acquired hashes and emit static Metro audio references."""
import hashlib,json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
sfx=json.loads((root/'app/assets/audio/sfx/manifest.json').read_text())['events']
music=json.loads((root/'app/assets/audio/music/manifest.json').read_text())['tracks']
ambience=json.loads((root/'app/assets/audio/ambience/manifest.json').read_text())
events=sfx+[{'id':t['id'],'bus':'music','files':[t],'gainDb':t['gainDb'],'cooldownMs':0,'maxConcurrent':1,'pitchRange':0,'duckMusicDb':0,'neutralVariant':None} for t in music]+[{'id':'ambience.main','bus':'ambience','files':ambience['files'],'gainDb':-30,'cooldownMs':0,'maxConcurrent':1,'pitchRange':0,'duckMusicDb':0,'neutralVariant':None}]
out=["// Generated by tooling/audio/build-registry.py from acquired manifests.","import type {AudioEventDefinition} from './AudioTypes';","export const audioEvents:Readonly<Record<string,AudioEventDefinition>>={"]
count=0
for event in events:
    fields={k:event[k] for k in ['id','bus','gainDb','cooldownMs','maxConcurrent','pitchRange','duckMusicDb','neutralVariant']}
    clips=[]
    for i,file in enumerate(event['files']):
        path=root/file['path'];assert path.is_file() and hashlib.sha256(path.read_bytes()).hexdigest()==file['sha256']
        clips.append('{key:'+json.dumps(event['id']+':'+str(i))+',source:require('+json.dumps('../../'+str(path.relative_to(root/'app')))+'),durationMs:'+str(file['durationMs'])+'}')
        count+=1
    out.append(json.dumps(event['id'])+':{'+json.dumps(fields,separators=(',',':'))[1:-1]+',files:['+','.join(clips)+']},')
out.append('};')
(root/'app/src/audio/AudioCatalog.ts').write_text('\n'.join(out)+'\n')
print(json.dumps({'status':'PASS','events':len(events),'files':count,'hashes':'PASS'}))
