import {test} from 'node:test';import assert from 'node:assert/strict';import {BoardPresenter} from '../../app/src/ui/BoardPresenter';import {layout} from '../../app/src/ui/ResponsiveLayout';import {Dispatcher} from '../../game-core/src/commands/Dispatcher';import {createState} from '../../game-core/src/model/GameState';import {heroes,mergeRules} from '../../game-core/src/content/PlayableConfig';import {mergeHeroes} from '../../game-core/src/commands/MergeHeroes';import {moveHero} from '../../game-core/src/commands/MoveHero';import {MemorySaveStore,FakeClock} from '../../game-core/src/ports';import {TransactionCoordinator} from '../../game-core/src/systems/TransactionCoordinator';import type {GameCommand,GameRuntime} from '../../app/src/game/GameRuntime';
test('presenter maps safe-area coordinates and cancellation/multi-pointer/stale/max drops preserve state',async()=>{
 const s=createState({dataVersion:'playable-v1',initialGold:'100',utcMs:0});s.data.heroes=[heroes.instantiate('hero_tier_10','a',0),heroes.instantiate('hero_tier_10','b',1)];s.data.board[0]!.unitId='a';s.data.board[1]!.unitId='b';
 let sequence=0;const dispatcher=new Dispatcher(s,(draft,c:GameCommand)=>c.type==='MergeHeroes'?mergeHeroes(draft,c,mergeRules,heroes,()=>[]):c.type==='MoveHero'?moveHero(draft,c):{ok:true,events:[]},new TransactionCoordinator(new MemorySaveStore(),new FakeClock(),'test').commit);
 const presenter=new BoardPresenter({dispatcher,nextId:()=>`drop_${++sequence}`} as unknown as GameRuntime),l=layout(390,844,{top:44,bottom:34,left:0,right:0});
 const r=l.toScreen(l.board[0]!);assert.equal(presenter.hit(r.x+r.width/2,r.y+20,l),0);const before=JSON.stringify(dispatcher.getSnapshot());
 assert.ok(presenter.begin(0,1));assert.equal(presenter.begin(1,2),null);presenter.cancel();assert.equal(await presenter.drop(1),null);assert.equal(JSON.stringify(dispatcher.getSnapshot()),before);
 presenter.begin(0);assert.deepEqual(await presenter.drop(1),{ok:false,reason:'MAX_TIER'});assert.equal(JSON.stringify(dispatcher.getSnapshot()),before);
 presenter.input.setLayer('modal',true);assert.equal(presenter.begin(0),null);presenter.input.setLayer('modal',false);
 presenter.begin(0);await dispatcher.dispatch({type:'DeployHero',commandId:'revision-change',heroId:'a',deployed:true});assert.deepEqual(await presenter.drop(2),{ok:false,reason:'STALE_REVISION'});assert.equal(dispatcher.getSnapshot().data.board[0]!.unitId,'a');
});
