import {test} from 'node:test';import assert from 'node:assert/strict';import {GameRuntime} from '../../app/src/game/GameRuntime';import {BattleRuntime} from '../../app/src/battle/BattleRuntime';import {stageHud} from '../../app/src/ui/StageHud';import {createState} from '../../game-core/src/model/GameState';import {heroes} from '../../game-core/src/content/PlayableConfig';import {MemorySaveStore,FakeClock} from '../../game-core/src/ports';import {TransactionCoordinator} from '../../game-core/src/systems/TransactionCoordinator';
export function productionFixture(stage='stage_1_1',tier=1){const state=createState({dataVersion:'playable-v1',initialGold:'100',utcMs:0,firstStage:stage,unlockedSlots:5}),h=heroes.instantiate(`hero_tier_${tier}`,'hero1',0);h.deployed=true;state.data.heroes=[h];state.data.board[0]!.unitId=h.id;state.data.progression.discoveredTiers=[tier];const store=new MemorySaveStore(),game=new GameRuntime(state,new TransactionCoordinator(store,new FakeClock(10),'test').commit),battle=new BattleRuntime(game);return {game,battle,store};}
export async function until(battle:BattleRuntime,condition:()=>boolean,max=1500){for(let i=0;i<max;i++){if(condition())return;battle.advance(50);await new Promise(r=>setImmediate(r));}throw Error('Simulation transition timed out');}
test('actual application reducer/runtime project sequential waves, first clear, boss timeout, farming and fresh retry',async()=>{
 const {game,battle}=productionFixture();const hud=()=>stageHud(game.dispatcher.getSnapshot(),battle.getSnapshot());assert.equal(hud().label,'1-1');assert.equal(hud().progress,0);
 await until(battle,()=>hud().label==='1-2');assert.equal(game.dispatcher.getSnapshot().data.currencies.gold,'106');await until(battle,()=>hud().waveLabel==='WAVE 2/2');assert.equal(game.dispatcher.getSnapshot().data.currencies.gold,'114');await until(battle,()=>hud().boss);assert.equal(hud().remainingSeconds,20);assert.equal(game.dispatcher.getSnapshot().data.currencies.gold,'142');
 await until(battle,()=>hud().farming&&hud().label==='1-2');assert.equal(hud().retryStageId,'stage_1_3');assert.equal(game.dispatcher.getSnapshot().data.progression.highestClearedOrdinal,2);const sequence=game.dispatcher.getSnapshot().data.stages.encounterSequence;
 assert.equal((await game.dispatcher.dispatch({type:'RetryBoss',commandId:'retry:visible',stageId:'stage_1_3',expectedSequence:sequence})).ok,true);assert.equal(hud().label,'1-3');assert.equal(hud().remainingSeconds,20);assert.equal(battle.engine.snapshot().encounter.sequence,sequence+1);assert.equal(battle.engine.snapshot().hits.length,0);battle.dispose();
});
