from system_doc import *

# Remaining systems use the same explicit A–R contract with system-specific algorithms.
remaining=[
('11_ENEMY_SYSTEM','Enemy lifecycle','Enemy definition vs spawned encounter entity; spawnOrdinal is stable order.',
'enter encounter, tick, damage result','enemy.spawned, enemy.died, encounter.completed','definitionId,entityId,encounterId,hp,alive,deathCommitted; runtime target/attack state',
'enemy definition and stage link exist; HP positive at spawn','spawn → damage clamp → alive→dead edge → reserve death reward → persist → remove logical entity → recycle view',
'SPAWNING→ALIVE→DYING_COMMITTED→REMOVED','if hpBefore>0 and hpAfter==0 and not deathCommitted: mark death once; enqueue unique reward(encounterId,entityId)',
'enemy.schema.json / stage.schema.json','SCREEN-003; enemy_* families and three boss_* dragon variants','enemy.spawn/idle/attack/hit/death; enemy.death.small/large',
'Save checkpoint must pair deathCommitted with reward receipt; reference HP restore U-013','enemy_kill aggregated, stage events','simultaneous hits; corpse pooling; despawn without death; missing art','unit death crossing once; integration1000 reused views cannot reuse logical IDs','EV-004 art; EV-012 live enemies','U-004,U-022,U-031','Zero duplicate death rewards; enemy visual may fade after logical removal; all live enemies have positive HP.'),
('12_STAGE_SYSTEM','Stage progression and farming','StageId is stable key; display chapter-stage, observed1-1 and1-9; encounter attempt differs from highest cleared stage.',
'boot, encounter complete, retry, boss clear','stage.entered, stage.cleared, stage.changed, unlock.available','currentStageId,highestClearedStageId,encounterSequence,farmingStageId,attemptId',
'Referenced wave/enemy/reward exist; previous critical reward persisted','resolve enemy/wave completion → reward transaction → advance highest clear if new → evaluate unlocks → persist next stage → emit',
'ENTERING→WAVE→COMBAT→REWARD→CLEAR→NEXT; boss failure→FARMING→RETRY','nextStage = stage.nextId; never parse display string for logic\nrewardKey includes encounterSequence for repeatable farming, firstClearKey includes stageId\nhighestCleared is monotonic; current farming stage may repeat',
'stage.schema.json/enemies/worlds/unlocks/rewards','SCREEN-003 label and enemy HP/stage track; progress semantics must be data-defined','stage.progress, stage.clear, currency gain','Persist attempt sequence and first-clear watermark atomically; no reward from stale previous generation','stage_start/clear, progression_monotonic test metric','last configured stage; missing nextId; repeat farming; pending projectile; retry','unit graph no dangling nextId, cycles allowed only explicit farming; integration double death one clear','EV-012 stage1-1→1-2; EV-014 farming1-9/boss retry visible','U-005,U-024,U-007','Progress advances only after eligible completion; first-clear reward once, repeat kill rewards use unique attempts; HUD is snapshot driven.'),
('13_BOSS_SYSTEM','Boss entry, timeout and retry','BossEncounter uses stage conditions, timer and special profile; no universal every-N formula without samples.',
'boss stage entered, retry tap, boss HP0, timer expiry','boss.warning, boss.started, boss.cleared, boss.failed','bossStageId,attemptId,remainingTicks,phase,retryAvailable,returnFarmStageId',
'Boss eligibility, roster, valid HP/timer config; previous attempt settled','enter warning → new generation → start timer → resolve lethal hits before timeout at same tick (PROPOSED tie rule) → win reward or fail/farm checkpoint',
'AVAILABLE→WARNING→COMBAT→CLEARED; COMBAT→TIMEOUT→FARMING→AVAILABLE','if boss.hp==0: settleWin once\nelse if tick>=deadline: settleFail; return to configured farming stage\nretry creates new attempt, never reuses reward key',
'stage.schema.json boss {timerTicks,retryPolicy,farmStageId}; enemy boss flag','SCREEN-003 warning/timer/retry; SCREEN-006 alt dragons not proof of stage-boss HP','boss.intro, boss.hit, boss.death; medium haptic once, HUD fixed','Persist failure/retry state and reward key; pause freezes simulation timer per proposed lifecycle policy','boss_start/clear/fail with stageId and attempt','lethal hit on deadline; restart mid-warning; spam retry; pending old projectile','unit deadline ordering; integration failure→farm→retry; native interruption','EV-014 retry prompt on1-9; exact first boss encounter requires video review','U-005,U-033','Win/fail mutually exclusive, at most one reward, retry no charge unless config explicitly observed; no permanent softlock.'),
('14_SKILLS_AND_SPECIALS','Skills and specials (conditional)','Skill=effect definition with duration/stack/target/cooldown; not ordinary attack animation.',
'Verified active/passive skill trigger only','skill.started, status.applied/expired if in scope','cooldown/status stacks plus duration ticks only for approved skills',
'Presence and mechanics verified; otherwise feature disabled','validate → cost/cooldown reserve → deterministic target list → effect resolve → durable grant if any → visual hooks',
'DISABLED; future READY→CASTING→COOLDOWN→READY','until observed: no skill commands accepted\nfuture effect ordering: expire→refresh/stack by explicit rule→recompute stats',
'skills.schema.json optional content; battle damage/target policies','No unverified button added to Figma main','hero.attack.magic profile does not imply gameplay skill; skill-specific hook only approved event','Do not create unused save fields except versioned empty capability collection','skill_used only if implemented','stack overflow, stun interrupt, expired caster','schema rejects unsupported effect; unit future refresh/stack rules','EV-004 magic-looking art only','U-021','Documented UNKNOWN and post-MVP gate; no invented skills reach MVP configs.'),
('15_DEATH_RESPAWN_RECOVERY','Death and recovery','Owned hero loss, temporary combat death, withdrawal and reserve state are distinct.',
'Enemy attack if verified, HP0, withdraw, recovery timer','hero.disabled/recovered or hero.withdrawn; no implicit item deletion','alive,recoverAtTick if applicable; persistent ownership remains until verified rule',
'Death mechanic enabled by observed config; absence of enemy damage evidence is not immortality proof','damage → dead transition once → remove from active roster → evaluate stall → recover by configured policy → restore eligible state',
'ACTIVE→DISABLED→RECOVERING→RESERVE; no-owned-unit deletion in proposed baseline','if noActiveHeroes: battle.state=STALLED\nprovide purchase/deploy/retry route; never delete roster because sprite death animation finished',
'hero/enemy/battle recovery policy','SCREEN-003 disabled visual and clear recovery label; no fake timer','hero.hit/death/recover; quiet failure feedback','Save ownership separately from encounter alive flag; migrate recover timestamps safely','battle_stalled, hero_recovered if enabled','all dead; revive after app pause; merge disabled unit; empty roster','unit no negative HP and ownership retention; integration restart during recovery','EV-011 withdrawal observed; true hero death not confirmed','U-022,U-013','No unverified permanent loss; stalled gameplay offers valid recovery input; future death rule has tests and save policy.'),
('16_BATTLE_CONTENT_MODES','Alternative battle contents','Content mode owns independent attempt/reward ledger and roster constraints; Dragon/Demon/Tower are advertised names.',
'EnterMode(modeId), retry/exit, encounter events after unlock','mode.entered/completed/failed; typed reward request','modeProgressById,attemptId,entryCostToken','P2 scope enabled; rules verified; no mixing stage reward identity with dungeon rewards','validate unlock/entry cost → durable attempt → mode simulation → settle outcome → return normal stage snapshot',
'LOCKED→AVAILABLE→ENTERING→ACTIVE→RESULT→AVAILABLE','modeAdapter provides encounter config and reward policy; reuse pure battle, never duplicate BattleSystem\nnormal stage suspended/continued only by explicit policy',
'modes.schema.json; stage/enemy/rewards','SCREEN-006 three dragon cards; alternate tower/castle screens require source capture','mode-specific background bundle, boss profile; unload after exit','Separate saved mode progress and first-clear rewards; entry cost and attempt id atomic','mode_start/complete/fail','exit before reward; resume; roster prohibited; entry token duplicate','schema references valid; unit attempt idempotency; integration normal stage unaffected','EV-006 advertised contents; EV-004 dungeon Figma','U-018','Post-MVP task gate is explicit; shared simulation reused; no invented content progression in MVP.'),
('17_TUTORIAL_SYSTEM','Data-driven tutorial','StepId persistent checkpoint; target semantic UI ID; tutorial input owner allows only required action.',
'Fresh save/version migration, command completed, popup acknowledged','tutorial.stepChanged/completed; overlay target/focus command','tutorialVersion,completedSteps,currentStepId; transient overlay pointer','Target exists and feature state eligible; already-completed event skips obsolete step','resolve required step → acquire input token → show hand/message → observe committed domain completion → checkpoint → release → advance',
'BUY_FIRST→BUY_SECOND→DRAG_SECOND_TO_FIRST→NEW_HERO_ACK→DRAG_TO_FIGHT→TAP_WITHDRAW→DRAG_TO_FIGHT_AGAIN→TUTORIAL_ACK→COMPLETE','step.completeOnlyOn = committed event or explicit popup acknowledgment\nif restored state already satisfies step: reconcile forward once\nif target missing: release lock, show retry/skip-safe diagnostic; never freeze app indefinitely',
'tutorial.schema.json targetId,eventFilter,allowInputs,skipPolicy,version','SCREEN-003 + proposed NewHero overlay; Figma hand asset gap; tutorial overlays block underlying clicks selectively','hand pulse, target highlight, ui.tap.primary; no endless full-screen blocking after completion','Persist completed steps with action transaction, not hand animation; migration maps stable step IDs','tutorial_step once per actual completion','close midstep; delayed target load; second tap too fast; missing node; old tutorial version','unit step advance only correct event; integration relaunch each step; manual full golden path','EV-009…011 two buys, drag, new hero, deploy/withdraw; current run completed tutorial acknowledgment','U-012 exact version; U-007 tutorial grants; U-030 later auto tutorial','Fresh run reaches free play; save at each step restores without double grant; no blocked invisible target; step order evidence-backed.')]
for r in remaining:
 system_doc('docs/gameplay/'+r[0]+'.md',*r[1:])

system_doc('docs/gameplay/06_BATTLE_SYSTEM.md','Deterministic battle simulation',
'EncounterId identifies one spawned enemy/wave; tick is fixed simulation time; presentation time is independent. Stage progress is separate from transient enemy HP.',
'Tick(deltaTicks), roster changed, enter stage, pause/resume, explicit retry; injected seeded RNG and config snapshot.',
'attack.intent, projectile.launched, damage.applied, enemy.died, reward.committed, stage.changed; ordered immutable event batch.',
'Persistent stage/highest clear and reward watermarks; encounter snapshot/checkpoint per save policy. Runtime combatants, cooldowns, projectiles {hitTick,attackId,targetId}, RNG cursor, encounter generation.',
'Validated definitions; spawned encounter; at least one active deployed hero for progress; app READY/foreground; pending durable reward blocks next stage.',
'At fixed tick: cooldown/update statuses → eligible target acquisition → attack intents sorted by instanceId → scheduled hits → damage → death once → reward draft → durable commit → stage transition. View never reports an authoritative damage result.',
'ENTERING_STAGE→SPAWNING_WAVE→COMBAT→ENEMY_DEATH→REWARD_COMMIT→STAGE_CLEAR→TRANSITION; boss stage inserts BOSS_WARNING→BOSS_COMBAT; timeout→STALLED; app pause preserves checkpoint.',
'advance(realDelta): accumulator+=min(realDelta,maxFrameDelta)\nwhile accumulator>=step && steps<maxCatchUp:\n tick++ ; resolveScheduledHits(tick,encounterGeneration)\n acquireTargets(); produceAttackIntents(); expireDeadTargets()\n accumulator-=step\nbackground delta is handled by OfflineService, never thousands of catch-up battle ticks',
'enemy.schema.json, hero.schema.json, stage.schema.json, battle.schema.json: stepMs=50 and maxCatchUp=5 are PROPOSED performance fixture, not measured attack speed.',
'SCREEN-003 world, damage labels and stage HUD; adapters index views by entityId. Keep HUD outside world shake layer.',
'hero.attack windup/release/recover; projectile.launch/travel/impact; hit/crit/death/reward profiles; audio from committed domain events only.',
'Economy always durable at death/stage boundaries. Proposed resume restarts current encounter with checkpoint roster and HP policy; no dead-enemy reward replay. Exact reference encounter persistence U-013.',
'stage_start/clear, boss_start/clear, error; optional combat traces only dev to avoid per-hit analytics traffic.',
'Two hits kill same tick; dead target hit; roster merge mid-attack; boss transition pending projectile; frame spike; pause during impact; no active hero; invalid config.',
'Unit deterministic same seed+commands; compare 16/33/100ms host frame partitions with same tick count. Integration 1000 progressions no deadlock/duplicate reward; mobile 30min soak.',
'EV-011 deployed Archer attacks automatically; EV-012 first enemy cleared, next stage visible and gold+1. Timing/formula not measured from static screenshot.',
'U-004 stats/timing, U-031 target policy, U-005 bosses, U-022 death, U-033 background/meta behavior.',
'Identical replay yields identical domain snapshot; no Cocos imports; every death transitions once; animation quality/time scale cannot alter combat result.')

system_doc('docs/gameplay/07_TARGETING_SYSTEM.md','Target acquisition and stale-target policy',
'TargetId is encounter-scoped enemy identity; target policy is ordered eligibility, not nearest visual sprite unless observed.',
'Attack readiness, target died/despawned, encounter changed, roster replacement.',
'target.acquired / target.lost; deterministic AttackIntent target reference.',
'Runtime targetId and encounterGeneration per combatant. No persistent pointer to a Cocos Node.',
'Target alive, correct encounter, legal class/range if enabled; attacker active.',
'Build eligible target list → sort by configured policy → stable tie-break spawnOrdinal then enemyId → emit intent; revalidate at hit.',
'NO_TARGET→ACQUIRED→LOST→NO_TARGET; encounter change invalidates all old targets.',
'PROPOSED choose min(spawnOrdinal,enemyId) among alive eligible enemies\nif intent.target generation != current: cancel\nif target died before impact: cancel hit; no auto-retarget until observed',
'battle.schema.json targetingPolicy, rangePolicy, staleProjectilePolicy. Unknown exact priority stays configurable.',
'SCREEN-003 target highlight optional debug-only; enemy HP bar attached to current entity.',
'Projectile cancellation fades/recycles without impact sound; no fake damage feedback on dead target.',
'Target references reset at encounter restore; stable IDs valid only in saved generation.',
'No production per-target event; debug trace includes decision order.',
'Equal-distance enemies, zero targets, dying same tick, new spawn reusing view, AoE unsupported.',
'Unit stable ties and stale generation rejection; integration two projectiles into dead target grants once; replay order unaffected by view insertion order.',
'EV-012 single early enemy seen; multi-target priority not established.',
'U-031 must close before REFERENCE_EXACT target policy.',
'All intents reference eligible current-generation entities; deterministic tie-break; pooled view reuse never redirects a logical hit.')

system_doc('docs/gameplay/08_ATTACK_SYSTEM.md','Attack cooldown and marker contract',
'AttackId = encounter + attacker + sequence. Logical windup/release/impact tick differs from visual animation duration.',
'Simulation tick and active target; stat/cooldown modifiers at documented boundaries.',
'attack.intent {attackId,attackerId,targetId,releaseTick,hitTick}; attack.cancelled; one resolved hit.',
'Runtime nextAttackTick, attackSequence, phase, scheduled intent. Config controls intervalTicks and windupTicks.',
'Active deployed alive attacker; target legal; tick>=nextAttackTick; no disabled status.',
'Reserve attack ID → choose target/stats snapshot → set nextAttackTick from prior schedule/current tick policy → enqueue logical hit → publish visual markers. Renderer follows tick schedule.',
'READY→WINDUP→RELEASED→RECOVER→READY; invalidation before release→CANCELLED; post-release projectile uses its own rule.',
'if tick>=nextAttackTick && target:\n intent = snapshotAttackStats()\n nextAttackTick=tick+intervalTicks\n scheduleHit(tick+windupTicks+travelTicks)\n emit marker schedule; renderer may catch up but cannot call damage twice',
'hero attack profiles + animation.schema.json releaseMarker; all durations centralized; no gameplay setTimeout.',
'HeroView body transform for flattened sprites; separate shadow; socket coordinates calibrated per visual profile.',
'hero.attack.melee/bow/magic; projectile.release; optional anticipation sound quiet. Attack cancellation stops loop sound, not currency.',
'Encounter checkpoint policy determines cooldown restore; pause/resume must not produce burst of missed offline attacks.',
'No per-hit production analytics; debug attackId and timeline trace.',
'Interval change during windup; merge attacker; pause before release; speed0.5/2x; large dt; missing sprite.',
'Unit exact scheduled tick count, no double hit on repeated marker; integration renderer frozen/dropped frames same domain result; 60fps video marker QA.',
'EV-012 ranged projectile visible; popup icon values including2.0 are display facts, not measured interval.',
'U-004 real intervals and marker location; U-023 merging deployed attacker.',
'Every attack has one logical release/hit schedule; cooldown monotonic; no duplicated marker damage; debug animation speed leaves domain intact when separately configured.')

system_doc('docs/gameplay/09_DAMAGE_CRIT_DEFENSE.md','Damage, defense and crit resolver',
'Damage is nonnegative integer; multipliers integer basis points (10000=1); RNG draws explicit; displayed attack may differ from effective damage.',
'AttackIntent immutable stat snapshot, defender stats, injectable RNG.',
'DamageResult {raw,crit,mitigated,applied,hpBefore,hpAfter,attackId}; death candidate if HP crosses zero.',
'Runtime HP and RNG cursor; definition/config immutable. Currency numerical representation separate from combat small integers.',
'Finite safe-integer combat stats or explicit bigint representation; probability within0..10000; multiplier valid; attackId unresolved.',
'Check intent uniqueness → draw crit once if applicable → calculate raw → defense → round at specified step → clamp applied to remaining HP → mark resolved → detect death crossing.',
'UNRESOLVED→RESOLVED_NORMAL/CRIT→APPLIED; duplicate→IGNORED; invalid config→ERROR.',
'PROPOSED fixture only:\ncrit = rngBp()<critChanceBp\nraw=floor(attack*(crit?critMultiplierBp:10000)/10000)\ndamage=max(1,raw-defense) for positive damaging intent\napplied=min(hp,damage); hp=max(0,hp-applied)\nReference formula remains UNKNOWN until fit validates samples.',
'battle.schema.json damageModel/rounding/minDamage; hero/enemy stats; proposed_balance_v1 separate from reference_balance_observed.',
'SCREEN-003 normal/crit damage labels; same number formatter as HUD; show zero/miss only if mechanics established.',
'hit.normal/hit.crit; crit label1.25× scale proposed; cap flash and camera/haptic rate, do not play once per every numeric digit.',
'HP checkpoint policy explicit; never persist post-death state without matching reward token/watermark.',
'Only aggregated battle metrics; no RNG/private state network disclosure.',
'Defense>=attack; zero/negative inputs; damage>HP; simultaneous attacks; crit0/100%; integer bounds; evade/block UNKNOWN.',
'Unit boundary probabilities, rounding and clamping; seeded distribution sanity; observed-data regression requires≥20 samples/tier/target; no formula promotion on one hit.',
'EV-004 Figma stat labels; EV-010 display values; neither proves formula.',
'U-004 and U-034; block reference balance import until residual analysis and rounding choice documented.',
'No NaN/negative HP/overflow; result reproducible; duplicate attack causes no mutation; every numeric constant either config fixture or evidence-backed.')

system_doc('docs/gameplay/10_PROJECTILE_SYSTEM.md','Logical projectiles and pooled presentation',
'Logical projectile = scheduled hit record; visual projectile = disposable pooled sprite. Only domain clock resolves damage.',
'attack.intent ranged; tick reaches hitTick; pause; encounter/target invalidation.',
'projectile.launched/impact/cancelled; one damage resolver call per attackId.',
'Runtime projectileId, attackId, targetId, encounterGeneration, launchTick,hitTick, stat snapshot. Renderer stores start/end socket positions.',
'Ranged attack valid; configured projectile profile exists; pool exhaustion cannot prevent logical hit.',
'Schedule logical record → acquire view if budget → interpolate against tick fraction → at hitTick revalidate target → resolve once → recycle all transient state.',
'SCHEDULED→IN_FLIGHT→IMPACTED→RECYCLED; stale target/encounter→CANCELLED→RECYCLED.',
'alpha=clamp((renderTick-launchTick)/(hitTick-launchTick),0,1)\nview.position=curve(socket,targetAnchor,alpha)\nonHitTick: if generation/target valid resolveDamage once else cancel\nrecycle resets opacity,scale,trails,listeners and target refs',
'projectiles.schema.json speed/travelTicks/visualId/trailProfile; animation markers; object-pool capacities.',
'SCREEN-003 ProjectileLayer below HUD and above combatants; separate debug socket overlay.',
'projectile.launch/travel/impact; release/impact audio; pooled trail and spark; LOW removes trails.',
'Proposed resume clears transient projectiles and restarts encounter consistently; alternative exact checkpoint must serialize hit schedule+resolved IDs together.',
'Pool misses and cancelled stale hits are dev/performance metrics.',
'Two projectiles same kill; target despawn; scene switch; zero travel ticks; pool exhausted; pause at impact; recycled generation.',
'Unit no duplicate hit; integration kill+stage boundary cancels stale projectile; stress pool reuse1000 cycles, allocations flat after warmup.',
'EV-012 visible Archer arrow in live screenshot; exact trajectory/impact timing unknown.',
'U-031 retarget; U-004 timing; U-026 sockets.',
'Presentation may be skipped without changing result; pool release always executes; no previous-stage projectile damages new enemy.')


system_doc('docs/gameplay/01_HERO_SYSTEM.md','Hero definitions and instances',
'Definition = reference hero identity/family/tier/stats. Instance = owned unit with stable instanceId. Tier is merge progression; hero upgradeLevel and accountLevel are separate. visualId is Figma art mapping, not a stat source.',
'purchase.succeeded, merge.completed, deploy/withdraw commands, upgrade transaction, tick.',
'hero.spawned, hero.deployed, hero.withdrawn, hero.statsChanged; immutable combat snapshots.',
'Persistent: instanceId, definitionId, tier, slotId, upgradeLevel, equippedItemIds, deployed, alive/recovery if verified. Runtime: targetId, cooldownTicks, attackSeq, transient buffs, presentation phase. Animation state is renderer-owned.',
'Definition exists; tier and visual profile valid; slot unique; deploy capacity available. Never infer family compatibility from portrait border color.',
'Validate command and config refs → compute candidate instance/stats → validate board+roster invariants → durable commit → emit one entity delta.',
'OWNED_RESERVE ↔ DEPLOYED → RECOVERING (only if measured) → OWNED_RESERVE; either owned state → CONSUMED_BY_MERGE.',
'effectiveStats = resolve(definition.baseStats, upgradeConfig, equippedItems, validBuffs)\nresolve emits no side effects; visualId comes from explicit content mapping\nconsumed instances are absent from board and roster after merge',
'hero.schema.json; hero-tiers.schema.json; equipment.schema.json; explicit tier→visual mapping. No balance in Cocos Component.',
'SCREEN-003 board/world, SCREEN-004 detail, SCREEN-007 list; HeroView/Portrait use semantic families hero_*, portrait_*.',
'hero.spawn, hero.idle, hero.attack, hero.hit, hero.merge_out/in; hero.spawn, hero.upgrade audio; view interruption reconciles instanceId.',
'Instances retain IDs across normal reload. Transient attack state either saved at defined checkpoint or deterministically reset at encounter restart; one policy per save version.',
'hero_tier_reached once per discovered tier; hero_deploy/withdraw optional debug traces.',
'Consumed deployed unit; duplicate ID; invalid definition; stale target; upgrade while firing; missing art; unknown max tier.',
'Unit: stats composition and ownership. Integration: board/roster referential integrity on merge+reload. Manual: portrait and world correspond to same visualId.',
'EV-004 Figma ten named archetypes; EV-010 live Archer tier2; these are different identity systems (CF-004).',
'U-023 deployment restrictions; U-022 recovery; U-035 reference/art correspondence; U-004 real stats.',
'Every live instance has one valid definition and at most one board position; deployed set references existing instances; view deletion cannot change ownership; no unresolved required data ref.')

system_doc('docs/gameplay/02_HERO_PURCHASE_SUMMON_SYSTEM.md','Hero purchase transaction',
'Buy means spending configured currency for a board unit. Summon/gacha and relic opening are separate commands and probability models.',
'BuyHero(commandId,offerId,expectedRevision); hold synthesizes repeated commands only when allowed; tutorial gate can accept a single named input.',
'purchase.succeeded {transactionId,instanceId,slotId,cost}; purchase.rejected {reason}; currency.changed; hero.spawned.',
'Persistent: purchaseCountByOffer, balances, board, nextInstanceSequence. Runtime: serialized command queue and per-pointer hold token.',
'Config valid; offer unlocked; currency >= cost; one unlocked empty slot after policy-defined existing cascade. Full board without free slot rejects with zero charge. Pending save blocks new economy mutation.',
'Read cost at execution revision → check slot and funds → allocate ID → subtract currency + increment count + add instance in same draft → persist → publish → optionally schedule auto scan. Gold is never spent from view animation.',
'IDLE → VALIDATING → COMMIT_PENDING → SPAWN_FEEDBACK → IDLE; validation failure → REJECTED → IDLE.',
'on Buy(cmd):\n if alreadyApplied(cmd.id): return priorReceipt\n price = offer.costAt(purchaseCount)\n slot = firstUnlockedEmptySlot(board)\n if slot == none: reject BOARD_FULL\n if balance < price: reject INSUFFICIENT\n commit(balance-price, count+1, newInstance(slot))\n emit success; if autoEligible: enqueue MergeScan',
'economy.schema.json offers, hero definitions and board slots; initial two observed buys cost1. Beyond those samples U-003; proposed fixture separated.',
'SCREEN-003 Buy buttons and HUD; badge/tier/cost runtime labels. Figma buy prices50/120 are golden-state fixtures only.',
'purchase.success/failure, hero.spawn animation; currency.gold.spend, hero.spawn, ui.error.currency audio; lightweight primary haptic.',
'Persist amount, count and instance atomically. Retry with same command ID returns receipt, no second charge. Crash before durable write is no purchase; after durable write restores unit.',
'hero_purchase {offerId,tier,currency,amount,transactionId}; currency_spent once after commit.',
'Exactly enough currency; one short; 20 taps; hold release outside canvas; full/locked board; app background mid-save; price changing after queued taps; max tier.',
'Unit: funds and count invariants; 20 queued buys accept exactly min(funds/price,free slots) when auto disabled. Integration crash at each boundary; manual hold/pointer cancel.',
'EV-009 first two buys 100→99→98 with price1, units in first empty positions. Hold tooltip observed after tutorial, exact cadence U-032.',
'U-003 price curve; U-032 hold/bulk; U-030 auto trigger; U-024 slot unlock; U-035 grant definition mapping.',
'Rejected action changes no persistent field; each accepted ID allocates exactly one unit and spends exactly one evaluated price; replay is idempotent and full board gives visible feedback.')

system_doc('docs/gameplay/03_MERGE_SYSTEM.md','Manual merge and atomic resolver',
'Compatible pair is configured family+tier equality with an available result definition. source = dragged unit; destination = drop target. Visual archetype is not compatibility.',
'MergePair(commandId,sourceId,destinationId,expectedRevision); only eligible tutorial pair accepted when forced tutorial active.',
'merge.completed {oldIds,newId,resultTier,destinationSlot,cascadeDepth,transactionId}; board.changed; hero.statsChanged; tier discovery reward request once.',
'Persistent board/units/roster/discoveredTiers; runtime drag pointer and pending revision. Domain never stores tween progress.',
'Different existing IDs; compatible and below max tier; neither consumed; source/destination owned. Policy for deployed pair must be locked via U-023 before exact implementation.',
'Validate both instances and slot ownership → compute new unit → remove both source IDs from board/roster → create one result at destination slot → optionally inherit destination deployment if policy permits → discover tier/reward once → persist one combined transaction → emit.',
'IDLE → DRAGGING → VALIDATING → COMMIT_PENDING → RESOLVED; invalid/cancel → IDLE without mutation.',
'merge(a,b): assert a.id != b.id && compatible(a,b)\nresult = config.result(a.definition,b.definition)\ndraft.remove(a); draft.remove(b)\ndraft.add(newId,result,b.slot)\nassert occupiedAfter == occupiedBefore-1\nassert unique(board.instanceIds)\ncommit and emit exactly one merge.completed',
'merge.schema.json compatibility/destination/max tier/deployed policy; hero-tiers.schema.json explicit result map.',
'SCREEN-003 drag highlight; invalid drop snaps back visually. Input owner releases on pointercancel, modal, pause or stale revision.',
'hero.merge_out, hero.merge_in, merge.low/mid/high, merge.cascade; sources visual-only snapshots survive logical removal until sequence ends; sound pitch bounded by depth.',
'Persist settled logical result before effect. Reload never reconstructs consumed units from effect progress. Discovery rewards in same durable transaction or separate persisted pending reward token.',
'hero_merge {fromTier,toTier,mode,depth,transactionId}; hero_tier_reached deduped by tier.',
'Three equal → result+one; four equal → two results before cascade; invalid family; self-drop; max tier; full board pair; deployed sources; pause/drop twice.',
'Unit: 2→1 count, destination, compatibility. Property: weighted tier mass conserved for power-of-two fixture, source IDs absent. Integration: duplicate command, crash while showing result; manual direction and hit regions.',
'EV-010 live two tier1→tier2 Archer; accepted tutorial drag from second slot onto first; no automatic merge while tutorial waited. This does not prove free-play pair priority.',
'U-002 auto ordering; U-023 deployed inheritance; U-035 result family/tier table. Safe resolver requires explicit config, no silently guessed original rule.',
'Exactly one result at configured destination; no source survives; no duplicate reward; same input/state yields same result; max tier rejects without losing units.')

system_doc('docs/gameplay/04_AUTO_MERGE_SYSTEM.md','Auto-merge scheduler and cascades',
'Auto eligibility = unlock + activation mode + optional expiry. Cascade depth counts merge operations caused by one scheduling root, distinct from hero tier.',
'BoardChanged after purchase/merge, activation command, resume with settled board. Never rescan in a renderer callback.',
'merge.scanCompleted; merge.completed per pair; cascade.completed {rootId,operations}; explicit no_pair/max_tier outcomes.',
'Persistent auto mode/expiry if reference requires, settled board. Runtime root transaction ID, pending operation queue, presentation batch cursor.',
'Feature eligibility verified; no tutorial prohibition; single serialized mutation owner; finite board and valid max tier. Unknown unlock/order gates block REFERENCE_EXACT mode.',
'Scan immutable board → deterministic choose pair → atomic resolver → rescan resulting board until no pair or budget → persist settled state per command boundary → emit ordered result batch. New buy commands queue after current batch.',
'DISABLED ↔ IDLE → SCANNING → RESOLVING → CASCADE → SCANNING; no pair → IDLE; pause → SUSPENDED → IDLE.',
'PROPOSED policy A (not observed ordering):\nwhile pair = firstCompatiblePairByAscendingSlot(board):\n  merge(pair.sourceHighSlot,pair.destinationLowSlot)\n  operations += 1\n  assert operations <= initialOccupiedCount-1\nreturn settledBoard, orderedEvents\nCandidate B tier-first and C purchase-fed remain capture alternatives, not simultaneous runtime policies.',
'merge.schema.json autoPolicy enum, activation rule, max tier, presentation batch max, expiry. Pair selector pure and injectable for observed policy replacement.',
'SCREEN-003 booster indicator/board; badge expiry if paid/timed proven; no invisible always-on default while tutorial requires drag.',
'Cascade visual intensity saturates at3; at most2 concurrent result bursts; queue remaining short feedback; preserve input responsiveness; merge.cascade audio same-sample cooldown.',
'Do not save half-consumed sources. If several pair operations are batched, save final candidate once; on write failure discard draft. Reload starts settled board and no replayed grants.',
'hero_merge(mode=auto), cascade_length; analytics never triggers next merge.',
'[1,1,2]→[3]; [1,1,1]→[2,1]; [1,1,1,1]→[3] under proposed policy; two disjoint families; full board pair frees one; only max-tier pairs do not loop.',
'Unit golden boards for each policy. Property/stress ≥1000 seeded boards: termination, deterministic output, no illegal tier/negative funds. Pause/save/rapid buy replay integration; 0.5/1/2x presentation QA.',
'EV-006 public description advertises auto; EV-009…010 tutorial manual. Runtime activation/order not yet proven.',
'U-002 and U-030 HIGH: implement configurable proposed fixture only until capture task closes. Verify new purchases during cascade and max tier explicitly.',
'Scheduler terminates within occupiedCount-1 operations, emits no duplicate commands, correctly settles full-board cascade; animation interruption cannot alter result; unknown ordering cannot be mislabeled reference exact.')

system_doc('docs/gameplay/05_BOARD_SLOT_SYSTEM.md','Board, placement and deployment',
'SlotId stable row-major index; occupancy distinct from unlock; deployed unit retains owned board slot in observed tutorial. Empty tile is not a battle position.',
'Purchase, merge, deploy, withdraw, slot unlock, pointer drop, lifecycle cancellation.',
'board.changed; slot.unlocked; hero.deployed/withdrawn; rejected action reason.',
'Persistent slots {id,unlockCondition,unitId}; deployed instance set; runtime selection/pointer owner. Proposed logical capacity15, initial5 based on web display.',
'One unit per slot; locked slots empty; no unit appears twice; deployment subset of owned units and below configured cap.',
'Resolve slot eligibility → validate ownership/revision → write occupancy/roster atomically → persist critical change → emit; display projection maps logical slots to responsive anchors.',
'LOCKED → EMPTY ↔ OCCUPIED_RESERVE ↔ OCCUPIED_DEPLOYED; merging removes one occupied position; unsupported sell disabled.',
'firstEmpty = lowest slotId with unlocked && unitId==null\non deploy(id): assert roster.size<cap; add id, keep slot occupied\non withdraw(id): remove id from deployed; retain unit+slot\non fullBoardPurchase: reject before spend; manual compatible merge remains possible',
'merge.schema.json board layout and deploy policy; unlocks.schema.json conditions; visual 430×932 ten-slot fixture separately.',
'SCREEN-003 Figma10 slots5×2 vs live15 positions5×3 CF-003; adapt elastic board and touch targets, do not silently reduce reference capacity.',
'board.slot.unlock glow once; hero selected ring; invalid drop shake; ui.locked, feature.unlock sound.',
'Store stable slot IDs, not visual coordinates. Schema migration adding slots preserves existing IDs and occupancy; invalid duplicates quarantined.',
'slot_unlock, hero_deploy, hero_withdraw; reject reasons debug-only aggregation.',
'Board full; all locked; last-slot merge; expired unlock; invalid save duplicate occupancy; drag outside; two pointers; buy+drop same frame; delete/sell unknown.',
'Unit placement first free; integration full board no charge; migrate10→15 fixture without moving old IDs; native touch cancellation; visual44px target at narrow screens.',
'EV-009 web15 positions,5 open; EV-011 deployed tag appears on retained board unit, tap withdraw. EV-004 Figma10.',
'U-024 labels 2/3/4/6/10/15/20 and gems need threshold-type verification; U-023 cap/merge restrictions; U-025 layout adaptation.',
'All board/roster invariants hold after every command and restore. Full board is recoverable by merge, no funds lost, UI states explicitly communicate locks.')
