from plan_common import *
S={'type':'string','minLength':1};ID={'type':'string','pattern':'^[A-Za-z][A-Za-z0-9_.:-]*$'};N={'type':'integer','minimum':0,'maximum':9007199254740991};POS={'type':'integer','minimum':1,'maximum':9007199254740991};AMT={'type':'string','pattern':'^(0|[1-9][0-9]*)$'};BOOL={'type':'boolean'}
def enum(*v):return {'enum':list(v)}
def arr(items,minimum=0):return {'type':'array','items':items,'minItems':minimum}
def obj(props,required=None):return {'type':'object','additionalProperties':False,'properties':props,'required':list(props) if required is None else required}
def mapping(value):return {'type':'object','additionalProperties':value}
def nullable(v):return {'anyOf':[v,{'type':'null'}]}
def ref(name):return {'$ref':f'https://kisel.invalid/schemas/{name}.schema.json'}
def schema(name,body):
 body={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':f'https://kisel.invalid/schemas/{name}.schema.json','title':name,'description':'PROPOSED planning contract. Validate cross-record references separately. Not reference balance.',**body};dump('data-spec/'+name+'.schema.json',body)
def collection(entry):return obj({'schemaVersion':{'const':1},'dataVersion':ID,'evidenceMode':enum('OBSERVED','MEASURED','DERIVED','PROPOSED'),'entries':arr(entry)})
rewardItem=obj({'kind':enum('currency','item','freeSpin'),'id':ID,'amount':AMT})
stats=obj({'attack':N,'defense':N,'hp':POS,'attackIntervalMs':POS,'critChanceBp':{'type':'integer','minimum':0,'maximum':10000},'critMultiplierBp':{'type':'integer','minimum':10000,'maximum':100000}})
schema('hero',obj({'id':ID,'family':ID,'tier':POS,'rarityId':nullable(ID),'attackType':enum('melee','ranged','magic'),'baseStats':stats,'visualId':ID,'portraitId':ID,'animationProfile':ID,'audioProfile':ID,'projectileId':nullable(ID),'unlockId':nullable(ID),'evidenceIds':arr(ID)}))
schema('heroes',collection(ref('hero')))
schema('hero-tiers',collection(obj({'id':ID,'tier':POS,'definitionId':ID,'nextDefinitionId':nullable(ID),'discoveryRewardId':nullable(ID),'upgradeCap':N,'levels':arr(obj({'level':N,'cost':AMT,'currencyId':ID,'attackBonus':N,'hpBonus':N}))})))
schema('enemy',obj({'id':ID,'boss':BOOL,'baseStats':stats,'visualId':ID,'animationProfile':ID,'audioProfile':ID,'rewardId':ID,'attackEnabled':BOOL,'evidenceIds':arr(ID)}))
schema('enemies',collection(ref('enemy')));schema('bosses',collection(ref('enemy')))
schema('stage',obj({'id':ID,'ordinal':POS,'chapter':POS,'displayIndex':POS,'worldId':ID,'waves':arr(obj({'enemyId':ID,'count':POS}),1),'firstClearRewardId':nullable(ID),'nextStageId':nullable(ID),'boss':nullable(obj({'timerMs':POS,'farmStageId':ID,'retryPolicy':enum('manual','automatic'),'tiePolicy':enum('lethal_before_timeout')})),'evidenceIds':arr(ID)}))
schema('stages',collection(ref('stage')))
schema('worlds',collection(obj({'id':ID,'nameKey':ID,'backgroundVisualId':ID,'stageIds':arr(ID,1)})))
schema('economy',obj({'schemaVersion':{'const':1},'dataVersion':ID,'evidenceMode':enum('OBSERVED','PROPOSED','DERIVED'),'currencies':arr(obj({'id':ID,'nameKey':ID,'iconVisualId':ID}),1),'offers':arr(obj({'id':ID,'currencyId':ID,'grantDefinitionId':ID,'prices':arr(AMT,1),'afterTable':enum('reject','repeatLastProposed'),'holdEnabled':BOOL,'holdIntervalMs':POS})),'offline':obj({'enabled':BOOL,'currencyId':ID,'capMs':N,'ratePerSecond':AMT,'advanceStages':{'const':False}})}))
schema('merge',obj({'schemaVersion':{'const':1},'manualEnabled':BOOL,'autoPolicy':enum('disabled','slotOrder','tierAscending','purchaseFed'),'autoUnlockId':nullable(ID),'compatibility':enum('sameFamilyAndTier','explicitPairs'),'pairs':arr(obj({'sourceDefinitionId':ID,'targetDefinitionId':ID,'resultDefinitionId':ID})),'manualDestination':{'const':'dropTarget'},'autoDestination':enum('lowerSlot','purchaseTarget'),'deployedPolicy':enum('reject','preserveDestination','inheritEither'),'maxTier':POS,'board':obj({'slotCount':POS,'columns':POS,'initialUnlocked':N,'deploymentCap':POS,'slotUnlockIds':arr(nullable(ID))})}))
schema('equipment',collection(obj({'id':ID,'slotType':ID,'allowedHeroFamilies':arr(ID),'rarityId':nullable(ID),'visualId':ID,'maxLevel':N,'levels':arr(obj({'level':N,'attackBonus':N,'hpBonus':N,'defenseBonus':N,'costCurrencyId':ID,'cost':AMT})),'setId':nullable(ID)})))
schema('rewards',collection(obj({'id':ID,'grants':arr(rewardItem),'repeatability':enum('once','period','encounter','spin'),'source':ID,'evidenceIds':arr(ID)})))
condition={'oneOf':[obj({'kind':{'const':'stageAtLeast'},'value':N}),obj({'kind':{'const':'accountLevelAtLeast'},'value':N}),obj({'kind':{'const':'tierAtLeast'},'value':N}),obj({'kind':{'const':'allOf'},'conditions':arr({'$ref':'#/$defs/condition'},1)}),obj({'kind':{'const':'anyOf'},'conditions':arr({'$ref':'#/$defs/condition'},1)})]}
schema('unlocks',{**collection(obj({'id':ID,'condition':{'$ref':'#/$defs/condition'},'popupKey':ID,'targetFeatureId':ID,'tutorialStepId':nullable(ID)})),'$defs':{'condition':condition}})
schema('quests',collection(obj({'id':ID,'eventType':ID,'targetCount':POS,'rewardId':ID,'nextQuestId':nullable(ID),'resetPolicy':enum('none','utcDay'),'unlockId':nullable(ID)})))
schema('daily-rewards',obj({'schemaVersion':{'const':1},'periodBasis':enum('utcDay','verifiedServerDay'),'streakPolicy':enum('independent','consecutive','cumulative'),'missedDayPolicy':enum('retain','reset'),'rewardIds':arr(ID,1),'evidenceMode':enum('PROPOSED','OBSERVED')}))
schema('wheel',obj({'schemaVersion':{'const':1},'freeCooldownMs':N,'priceCurrencyId':nullable(ID),'price':AMT,'outcomes':arr(obj({'id':ID,'segmentId':ID,'weight':POS,'rewardId':nullable(ID),'freeSpins':N}),1),'segments':arr(obj({'id':ID,'labelKey':ID,'angleDegrees':{'type':'number','minimum':0,'exclusiveMaximum':360}}),1),'evidenceMode':enum('PROPOSED','OBSERVED')}))
schema('animation',collection(obj({'id':ID,'trigger':ID,'durationMs':N,'easing':ID,'releaseMarkerMs':nullable(N),'vfxId':nullable(ID),'audioEventId':nullable(ID),'hapticId':nullable(ID),'interruptPolicy':enum('cancelAndReconcile','finishCriticalMarker','resumeFromState'),'pooled':BOOL,'maxConcurrent':POS,'qualityFallback':ID})))
schema('audio-event',collection(obj({'id':ID,'trigger':ID,'bus':enum('music','sfx','ui','ambience','voice'),'variants':POS,'pitchMin':{'type':'number','minimum':0.5,'maximum':2},'pitchMax':{'type':'number','minimum':0.5,'maximum':2},'gainDb':{'type':'number','minimum':-96,'maximum':0},'cooldownMs':N,'maxConcurrent':POS,'duckMusicDb':{'type':'number','minimum':-24,'maximum':0},'sourceStatus':enum('placeholder','custom_needed','licensed','generated','final'),'licenseId':nullable(ID)})))
schema('battle',obj({'schemaVersion':{'const':1},'stepMs':POS,'maxCatchUp':POS,'targetingPolicy':enum('spawnOrder','nearest','verified'),'staleProjectilePolicy':enum('cancel','retargetVerified'),'damageModel':enum('proposedSubtractDefense','verified'),'rounding':enum('floor','round','ceil'),'minimumDamage':N,'encounterRestore':enum('restartEncounter','exactCheckpoint')}))
schema('projectiles',collection(obj({'id':ID,'visualId':ID,'travelMs':N,'trailProfile':nullable(ID),'impactVfxId':nullable(ID),'audioEventId':nullable(ID)})))
schema('tutorial',collection(obj({'id':ID,'targetUiId':ID,'completionEvent':ID,'allowedInputs':arr(ID),'messageKey':ID,'nextId':nullable(ID),'skipAllowed':BOOL,'version':POS})))
schema('modes',collection(obj({'id':ID,'unlockId':ID,'entryRewardTokenType':nullable(ID),'stageIds':arr(ID,1),'rosterLimit':POS,'rewardId':ID,'returnPolicy':enum('resumeStage','restartEncounter')})))
schema('summon',obj({'enabled':BOOL,'poolVersion':ID,'entries':arr(obj({'definitionId':ID,'weight':POS}),1),'currencyId':ID,'costOne':AMT,'costTen':AMT,'pityLimit':nullable(POS)}))
schema('skills',collection(obj({'id':ID,'cooldownMs':POS,'durationMs':N,'targetPolicy':ID,'effectType':enum('damage','statModifier'),'magnitude':N,'stackPolicy':enum('replace','refresh','stack'),'maxStacks':POS})))
schema('prestige',obj({'enabled':{'const':False},'reason':{'const':'UNKNOWN_OUT_OF_SCOPE'}}))
heroInstance=obj({'id':ID,'definitionId':ID,'slotId':N,'tier':POS,'upgradeLevel':N,'deployed':BOOL,'equippedItemIds':arr(ID)})
itemInstance=obj({'id':ID,'definitionId':ID,'level':N,'ownerHeroId':nullable(ID),'slotType':ID})
receipt=obj({'id':ID,'source':ID,'generation':N,'grants':arr(rewardItem)})
claim=obj({'id':ID,'source':ID,'fromAt':N,'toAt':N,'grants':arr(rewardItem),'status':enum('pending','committed')})
saveData=obj({'player':obj({'accountLevel':POS,'xp':AMT,'tutorialVersion':POS,'completedTutorialSteps':arr(ID)}),'currencies':mapping(AMT),'heroes':arr(heroInstance),'board':arr(obj({'slotId':N,'unlocked':BOOL,'unitId':nullable(ID)})),'progression':obj({'discoveredTiers':arr(POS),'highestClearedOrdinal':N,'purchaseCounts':mapping(N)}),'stages':obj({'currentStageId':ID,'encounterSequence':N,'bossRetryAvailable':BOOL,'farmStageId':nullable(ID)}),'unlocks':obj({'unlockedIds':arr(ID),'announcedIds':arr(ID)}),'equipment':arr(itemInstance),'quests':mapping(obj({'count':N,'period':S,'claimed':BOOL})),'daily':obj({'lastClaimedPeriod':nullable(N),'attendanceIndex':N}),'wheel':obj({'nextFreeAt':N,'freeSpins':N,'pendingSpin':nullable(obj({'id':ID,'outcomeId':ID,'rewardId':nullable(ID),'status':enum('reserved','committed')}))}),'offline':obj({'lastProcessedAt':N,'pendingClaim':nullable(claim)}),'settings':obj({'musicGain':{'type':'number','minimum':0,'maximum':1},'sfxGain':{'type':'number','minimum':0,'maximum':1},'haptics':BOOL,'reducedMotion':BOOL,'notifications':BOOL}),'analyticsConsent':enum('unknown','denied','granted'),'transactionReceipts':arr(receipt),'sourceWatermarks':mapping(N)})
schema('save',obj({'schemaVersion':{'const':1},'dataVersion':ID,'revision':N,'generation':N,'createdAt':N,'updatedAt':N,'lastActiveAt':N,'data':saveData}))
messageTypes=['game.ready','game.error','game.exitRequested','progress.stageChanged','currency.changed','reward.claimed','purchase.requested','ad.rewardRequested','analytics.event','save.changed','player.levelChanged','app.initialize','app.userChanged','app.purchaseResult','app.rewardGranted','app.pause','app.resume','app.settingsChanged','app.deepLink','app.notificationOpened']
schema('bridge',obj({'version':{'const':1},'type':enum(*messageTypes),'requestId':nullable(ID),'sessionId':ID,'generation':N,'sequence':N,'timestamp':N,'payload':{'type':'object'}}))
schema('bridge-payloads',{'$defs':{t:obj({'eventId':ID,'data':{'type':'object'}}) for t in messageTypes},'description':'Payload details are further constrained by bridge-protocol.json per message. No unknown keys at envelope level.'})
dump('data-spec/reference_balance_observed.json',{'status':'OBSERVED_DISPLAY_ONLY','platform':'CrazyGames web','captureDate':'2026-09-08','runtimeVersion':None,'samples':[{'sampleId':'BAL-001','kind':'initial_gold','value':'100','source':'analysis/reference/screenshots/web_ready.png'},{'sampleId':'BAL-002','kind':'purchase_quote','purchaseIndex':0,'value':'1','source':'analysis/reference/screenshots/web_ready.png'},{'sampleId':'BAL-003','kind':'purchase_quote','purchaseIndex':1,'value':'1','source':'analysis/reference/screenshots/tutorial_after_1.png'},{'sampleId':'BAL-004','kind':'first_tier2_discovery_gold','value':'10','source':'analysis/reference/screenshots/run2_reverse_merge.png'},{'sampleId':'BAL-005','kind':'first_tier2_discovery_gem','value':'100','source':'analysis/reference/screenshots/run2_reverse_merge.png'}],'formulas':[]})
dump('data-spec/proposed_balance_v1.json',{'status':'PROPOSED_NOT_REFERENCE','purpose':'isolated development fixture; never production parity import','initialGold':'100','purchaseCost':'1','attack':1,'attackIntervalMs':1000,'enemyHp':4,'killRewardGold':'1','offlineRatePerSecond':'1','offlineCapMs':28800000,'critChanceBp':0,'critMultiplierBp':15000,'maxTier':3,'dailyRewardGold':'10','wheelWeights':[1,1,1,1,1,1,1,1,1,1,1,1]})
names=sorted(p.stem.replace('.schema','') for p in (ROOT/'data-spec').glob('*.schema.json'))
write('data-spec/README.md','# Data contracts\n\n[PROPOSED] JSON Schema draft2020-12. These are planning artifacts, not production data. Strict object keys except intentional maps/event payload extensions. Monetary amounts are canonical decimal strings; combat values safe nonnegative integers; multipliers in basis points. Schema validation is necessary but does not validate semantic cross-references by itself.\n\n'+table(['Schema','Purpose'],[(f'[{n}]({n}.schema.json)','single record' if n in ['hero','enemy','stage'] else 'versioned configuration / state contract') for n in names])+'''\n\n## Data-file mapping and cross-validation

Future heroes.json→heroes.schema;hero-tiers.json→hero-tiers;enemies.json→enemies;bosses.json→bosses;stages.json→stages;worlds.json→worlds;economy.json→economy;merge.json→merge;unlocks.json→unlocks;equipment.json→equipment;rewards.json→rewards;quests.json→quests;wheel.json→wheel;daily-rewards.json→daily-rewards;animations.json→animation;audio-events.json→audio-event. Extra skills/projectiles/modes/tutorial only when required. All filenames above are future paths under cocos-game/assets/game-data, not created in planning.

Cross validators: unique IDs; all definition/asset/profile/localization refs exist; merge result tier advances validly; unlocked slot count≤capacity; deploy subset owned; wheel weights sum>0 and each outcome maps one segment; total spin free grants nonnegative; stage.next references valid except explicit end; boss farm stage valid; no orphan item refs; source watermark matches reward receipt; timestamp order from≤to; sum integer bounds. Reject PROPOSED content in reference-parity/release build unless explicit fidelity decision records it.

Schema default does not mutate data. Empty observed formula table means unknown. [Observed balance](reference_balance_observed.json) and [proposed fixture](proposed_balance_v1.json) never merge implicitly. Bridge payloads have a per-message contract in [bridge protocol](../docs/technical/18_BRIDGE_PROTOCOL.md); extend payload schemas before native production.

[Technical data](../docs/technical/07_CONFIG_AND_DATA_SCHEMAS.md) · [Tasks](../tasks/TASK_INDEX.md) · [Index](../docs/00_INDEX.md).
''')
