#!/usr/bin/env python3
"""Verify production subset compatibility and emit the spike's shared schema constants."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
spike = ROOT / 'spikes/rn-cocos'
schema = json.loads((spike / 'bridge-probe.schema.json').read_text())
production = json.loads((ROOT / 'data-spec/bridge.schema.json').read_text())
payloads = json.loads((ROOT / 'data-spec/bridge-payloads.schema.json').read_text())['$defs']
for name in ('game.ready', 'app.initialize'):
    assert schema['$defs'][name] == payloads[name], name
for name, value in production['properties'].items():
    if name != 'type':
        assert schema['properties'][name] == value, name
assert schema['required'] == production['required']
body = {key: schema[key] for key in ('type', 'properties', 'required', 'additionalProperties')}
target = spike / 'cocos-probe/assets/scripts/protocol/Schema.ts'
target.write_text('// Generated by tools/analysis/generate_spike_schema.py; development-only fixture.\n'
                  + 'export const envelopeSchema = ' + json.dumps(body, separators=(',', ':')) + ';\n'
                  + 'export const payloadSchemas = ' + json.dumps(schema['$defs'], separators=(',', ':')) + ';\n')
print('Spike schema preserves production envelope fields and two handshake payloads.')
